pipeline{
agent any

stages{
    stage('Build'){
        steps{
            echo "this is buid stage"
        }
    }
    stage('Test'){
        steps{
            echo "this is the test stage"
        }
    }
    stage('Deploy'){
        steps{
            echo "this is the deploy stage"
        }
    }
}
}